name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract Git Tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ env.RELEASE_VERSION }}
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        echo $IMAGE_TAG
        echo $GITHUB_REF
        echo "${{ secrets.DOCKER_PWD }}" | docker login -u "sureshnikuliya01" --password-stdin
        docker image build -t sureshnikuliya01/argocd-app:$GITHUB_REF_NAME .
        docker push sureshnikuliya01/argocd-app:$GITHUB_REF_NAME
