name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract Git Tag
      run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ env.GIT_TAG }}
      run: |
        echo "${{ secrets.DOCKER_PWD }}" | docker login -u "sureshnikuliya01" --password-stdin
        docker image build -t sureshnikuliya01/argocd-app:$IMAGE_TAG .
        docker push sureshnikuliya01/argocd-app:$IMAGE_TAG
